### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/caramel#2]
## Google Fonts Latin Plus coverage

- [x] Design all the glyphs required in the [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [x] Create all the comb marks as mentioned below
- [x] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back, so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and matching the style of the typeface design.
- [x] Adjust and align the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

![Screen Shot 2021-06-29 at 12 43 57](https://user-images.githubusercontent.com/48698976/123883957-b63b2b80-d90f-11eb-8a9b-b6d102d8a64f.png)
![Screen Shot 2021-06-29 at 12 44 26](https://user-images.githubusercontent.com/48698976/123883965-b804ef00-d90f-11eb-9ce9-8753c854f93d.png)

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference

![Screen Shot 2021-06-29 at 19 25 42](https://user-images.githubusercontent.com/48698976/123884053-e682ca00-d90f-11eb-8403-374ed00dd582.png)

**Comment by RobLeuschke** [comment]
@vv-monsalve 
Do you want the mod apostrophe's to have (0) sidebearings like the rest of the diacritic marks. I have added space on the left side to prevent them from crashing. Please advise. Thanks!
![image](https://user-images.githubusercontent.com/57553693/124163934-c1a06b00-da65-11eb-8895-d550bb6a7886.png)

**Comment by RobLeuschke** [comment]
I have completed all of the above tasks. Please note that many of the combination glyphs were decomposed and will need to be replaced with the component characters.

**Comment by vv-monsalve** [comment]
> Do you want the mod apostrophe's to have (0) sidebearings like the rest of the diacritic marks.

Yes, please. We'll avoid the crash when applying and positioning the anchors.

**Comment by vv-monsalve** [comment]
> I have completed all of the above tasks. Please note that many of the combination glyphs were decomposed and will need to be replaced with the component characters.

@RobLeuschke in spite of you are no generating the compound glyphs, it is necessary for you to try the marks in some letters to ensure the best proportions. E.g. `ring` looks bigger and lighter than the other marks; `cedilla`  and `ogonek` look huge and heavy (particularly cedilla).

<img width="591" alt="Screen Shot 2021-07-02 at 04 45 38" src="https://user-images.githubusercontent.com/48698976/124256799-500dfe80-daf1-11eb-9a47-0ecc4a7dd765.png">

The size of the original `cedilla` (in the background) looked more close to the ideal size while the stroke of the new one is more suitable

<img width="247" alt="Screen Shot 2021-07-02 at 04 50 16" src="https://user-images.githubusercontent.com/48698976/124257118-a7ac6a00-daf1-11eb-869c-9df43ec7442b.png">

**Comment by RobLeuschke** [comment]
I think this is better:
![image](https://user-images.githubusercontent.com/57553693/124321611-9f7d1a80-db43-11eb-91f8-5fcfa57a3a7b.png)
